### ISSUE TITLE
No IP address on the Configuration -> Network page

### ISSUE THREAD

**Issue by arthursw** [vogelbac/LAB-QA2GO#7]
### Summary

I successfully installed and launch the VM on my machine (using VirtualBox 5 on Ubuntu 18.04.4 LTS ) ; but there is no IP address displayed on the *Configuration -> Network* page : 

<img width="822" alt="image" src="https://user-images.githubusercontent.com/1814799/101505141-503b8680-3974-11eb-83d7-f672b61f27dc.png">

Maybe the problem comes from the network settings of the VM ; but I don't know what to chose. I have tried multiple things (VM Network Settings > Attach to NAT / NAT Network / Bridged Adapter, etc.) without success.

Which VM Network Settings should I use?

**Comment by vogelbac** [comment]
Hey I am sorry to hear this, and sorry for my late response.

you can try Host-Only Adapter, virtualbox host-only ethernet adapter. this should result that you have access from your pc over localhost. 

did you restart the VM after changing the adapter settings?

**Comment by arthursw** [comment]
I'm sorry I stopped working on Quality Control, so I won't need the tool anymore.

**Comment by vogelbac** [comment]
Oh i'm sorry for this and sorry for my late response. but if you have any other issues feel free to contact, even if you want to restart with quality control.

**Comment by arthursw** [comment]
Thanks :) !
